server:
  port: 8001
spring:
  application:
    name: y-cloud-consumer

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
logging:
  level:
    root: INFO